# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Activate the recommended Flutter lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: warning
    dead_code: error
    unused_import: warning
    unused_local_variable: warning
    todo: ignore
    missing_required_param: warning
    deprecated_member_use: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/generated_plugin_registrant.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    number-of-arguments: 4
    number-of-methods: 10
    maximum-nesting: 5
    source-lines-of-code: 50
    maintainability-index: 80
  rules:
    - avoid-nested-conditional-expressions
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-collection-methods-with-unrelated-types
    - avoid-redundant-async
    - avoid-unnecessary-type-parameters
    - avoid-unnecessary-nullable-parameters
    - avoid-unnecessary-nullable-return-types
    - avoid-unnecessary-nullable-variables
    - avoid-unnecessary-nullable-fields
    - avoid-unnecessary-nullable-methods
    - avoid-unnecessary-nullable-constructors
    - avoid-unnecessary-nullable-classes
    - avoid-unnecessary-nullable-extensions
    - avoid-unnecessary-nullable-typedefs
    - avoid-unnecessary-nullable-enums
    - avoid-unnecessary-nullable-annotations
    - avoid-unnecessary-nullable-imports
    - avoid-unnecessary-nullable-exports
    - avoid-unnecessary-nullable-parts
    - avoid-unnecessary-nullable-part-ofs
    - avoid-unnecessary-nullable-directives
    - avoid-unnecessary-nullable-comments
    - avoid-unnecessary-nullable-documentation
    - avoid-unnecessary-nullable-metadata
    - avoid-unnecessary-nullable-attributes
    - avoid-unnecessary-nullable-decorators

linter:
  rules:
    # Error rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps

    # Style rules
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_extensions
    - cascade_invocations
    - comment_references
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - implementation_imports
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_logic_in_create_state
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - provide_deprecation_message
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unsafe_html
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - void_checks
    - avoid_shadowing_type_parameters
    - overridden_fields
    - parameter_assignments
    - prefer_contains
    - prefer_mixin
    - recursive_getters
    - unnecessary_await_in_return
    - unnecessary_const
    - hash_and_equals
    - avoid_equals_and_hash_code_on_mutable_classes



# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
